version: '3'

services:

  django:
    build: .
    container_name: django
    command: bash -c "python manage.py makemigrations && python manage.py migrate
     && python manage.py load_data uszips.csv && python manage.py create_cars && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
      - celery
      - redis

  celery:
    build: .
    container_name: celery-worker
    command: celery -A trucking_services worker -l INFO -B
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=my_postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    ports:
      - "5432:5432"
#    volumes:
#      - ./pgdata:/var/lib/postgresql/data
#
#volumes:
#  pgdata:
